### ISSUE TITLE
Key classes missing javadoc 

### ISSUE THREAD

**Issue by pollend** [Terasology/BlockNetwork#5]
- [x] BlockNetworkUtil.java
- [x] EfficientBlockNetwork.java
- [x] EfficientNetwork.java
- [x] EfficientNetworkTopologyListener.java
- [x] ImmutableBlockLocation.java
- [x] Network.java
- [ ] TwoNetworkNodes.java

**Comment by thejmarie** [comment]
I added JavaDocs to the ImmutableBlockLocation.java file, and sent a pull request for it a couple of minutes ago.

**Comment by FieryPhoenix909** [comment]
I adda JavaDocs to TwoNetworkNodes.java and have made a pull request. #7

**Comment by skaldarnar** [comment]
Closing as mostly done!
